language: c
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libc6

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PREMAKE5=dep/bin-linux/premake5; else export PREMAKE5=dep/bin-osx/premake5; fi
  - chmod +x $PREMAKE5

script:
  - make linux-release-x64
