language: c
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

os:
  - linux

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libc6; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then PREMAKE5=dep/bin-linux/premake5; else PREMAKE5=dep/bin-osx/premake5; fi

script:
  - make linux-release-x86
  - make linux-release-x64
