language: c

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PREMAKE5=dep/bin-linux/premake5; else export PREMAKE5=dep/bin-osx/premake5; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export BD_NINJA=dep/bin-linux/ninja; else export BD_NINJA=dep/bin-osx/ninja; fi
  - chmod +x $PREMAKE5
  - chmod +x $BD_NINJA

script:
  - make -f quick.make linux-release-x64
  - make -f quick.make test

cache:
  build: true
