language: c
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

os:
  - linux

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:pasgui/ppa; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y premake5; fi

script:
  - make linux-release-x86
  - make linux-release-x64
